token: "<bot token here>"
sharding:
  max: auto
responses:
  "@onlymention":
    embed:
      title: Hi I'm @name
      description: "I was developed by tehZevo#0321. To donate or find out more about his projects, visit [zevo.me](https://zevo.me)."
      url: https://zevo.me
      color: 0x88ffaa
      footer:
        icon_url: https://cdn.discordapp.com/avatars/92442066080010240/cdadf6c70c6af986ab621e64ec533b6f.webp?size=128
        text: Developed by tehZevo#0321
      thumbnail:
        url: "@avatar"
      fields:
      - name: Guilds
        value: "@guilds"
        inline: true
      - name: Users
        value: "@users"
        inline: true
      - name: Invite me
        value: "[Click here!](@invite)"
        inline: true
      - name: Shard
        value: "@shard/@shards"
        inline: true
      - name: Uptime
        value: "@uptime"
        inline: true
      - name: Ping
        value: "@ping"
        inline: true
